<a href="https://colab.research.google.com/github/pranavik24/PromptInject/blob/main/notebooks/comparisons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sentence-transformers
!pip install rouge-score

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.28.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge-score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (4.67.3)
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=74ec18aca0e61ced169ddffc96bf19116bf124a8f3998f8d2b8098163c293018
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score
Successfully installed rouge-score-0.1.2

In [10]:
%cd /content/drive/MyDrive
! git clone https://github.com/pranavik24/PromptInject.git
%cd PromptInject
!git pull

/content/drive/MyDrive
fatal: destination path 'PromptInject' already exists and is not an empty directory.
/content/drive/MyDrive/PromptInject
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 95.50 KiB | 74.00 KiB/s, done.
From https://github.com/pranavik24/PromptInject
   275909f..d9e75be  main       -> origin/main
Updating 275909f..d9e75be
Fast-forward
 notebooks/BinaryClassification.ipynb   | 4117 ++++++++++++++++----------------
 notebooks/Generate_Clean_withCOT.ipynb |  398 ++-
 2 files changed, 2296 insertions(+), 2219 deletions(-)

In [1]:
!git config --global user.email "elainego@andrew.cmu.edu"
!git config --global user.name "Elaine Gombos"
!git add .
!git commit -m "Update with graphs and tables"

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

In [2]:
import pandas as pd
import re
import math
from sentence_transformers import SentenceTransformer
import numpy as np
from rouge_score import rouge_scorer

In [1]:
# Cell 1 — mount google drive
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [4]:
model = SentenceTransformer("all-mpnet-base-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [5]:

def encode_outputs(outputs1: list[str], outputs2: list[str], batch_size: int = 32):
    vecs1 = model.encode(outputs1, batch_size=batch_size, show_progress_bar=True)
    vecs2 = model.encode(outputs2, batch_size=batch_size, show_progress_bar=True)
    return vecs1, vecs2

In [6]:

def compute_cosine_scores(vecs1: np.ndarray, vecs2: np.ndarray) -> np.ndarray:
    norms1 = np.linalg.norm(vecs1, axis=1, keepdims=True)
    norms2 = np.linalg.norm(vecs2, axis=1, keepdims=True)
    return np.round(np.sum((vecs1 / norms1) * (vecs2 / norms2), axis=1), 4)

In [7]:
def compute_rouge_scores(outputs1: list[str], outputs2: list[str]) -> tuple[list, list]:
    scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2"], use_stemmer=True)
    rouge1_scores, rouge2_scores = [], []
    for o1, o2 in zip(outputs1, outputs2):
        scores = scorer.score(o1, o2)
        rouge1_scores.append(round(scores["rouge1"].fmeasure, 4))
        rouge2_scores.append(round(scores["rouge2"].fmeasure, 4))
    return rouge1_scores, rouge2_scores

In [10]:
def compare_model_outputs(path_without_cot: str, path_with_cot: str, output_path: str):
    df1 = pd.read_csv(path_without_cot)
    df2 = pd.read_csv(path_with_cot)

    assert len(df1) == len(df2), "CSVs have different number of rows"

    outputs1 = df1["output_text"].astype(str).tolist()
    outputs2 = df2["output_text"].astype(str).tolist()

    print("Encoding outputs...")
    vecs1, vecs2 = encode_outputs(outputs1, outputs2)

    print("Computing cosine similarity scores...")
    cosine_scores = compute_cosine_scores(vecs1, vecs2)

    print("Computing ROUGE scores...")
    rouge1_scores, rouge2_scores = compute_rouge_scores(outputs1, outputs2)

    pd.DataFrame({
        # "number": df1["number"],
        "prompt_instruction": df1["system_prompt"],
        "attack_instruction": df1["attack_name"],
        "output_WithoutCOT": df1["output_text"],
        "output_WithCOT": df2["output_text"],
        "cosineSimilarityScore": cosine_scores,
        "rouge1": rouge1_scores,
        "rouge2": rouge2_scores,
    }).to_csv(output_path, index=False)
    print(f"Done. Results saved to {output_path}")

In [12]:
compare_model_outputs(
    path_without_cot="/content/drive/MyDrive/11711 group project/elaine work/noinjection_withoutCOT_dup.csv",
    path_with_cot="/content/drive/MyDrive/11711 group project/elaine work/noinjection_withCOT_dup.csv",
    output_path="/content/drive/MyDrive/11711 group project/elaine work/noinjection_comparison_results.csv",
)

Encoding outputs...

Batches:   0%|          | 0/17 [00:00<?, ?it/s]

Batches:   0%|          | 0/17 [00:00<?, ?it/s]

Computing cosine similarity scores...
Computing ROUGE scores...
Done. Results saved to /content/drive/MyDrive/11711 group project/elaine work/noinjection_comparison_results.csv

In [2]:
import pandas as pd
import numpy as np

# Update this path to wherever compare_model_outputs() saved its output
COMPARISON_CSV = "/content/drive/MyDrive/11711 group project/elaine work/noinjection_comparison_results.csv"

df = pd.read_csv(COMPARISON_CSV)

print(f"Loaded {len(df)} rows")
print(f"Columns: {df.columns.tolist()}")
print()
print(df[["prompt_instruction", "attack_instruction", "rouge1", "rouge2", "cosineSimilarityScore"]].head(5))

Loaded 525 rows
Columns: ['prompt_instruction', 'attack_instruction', 'output_WithoutCOT', 'output_WithCOT', 'cosineSimilarityScore', 'rouge1', 'rouge2']

  prompt_instruction attack_instruction  rouge1  rouge2  cosineSimilarityScore
0    default-grammar              clean  0.0889     0.0                   0.16
1    default-grammar              clean  0.0889     0.0                   0.16
2    default-grammar              clean  0.0889     0.0                   0.16
3    default-grammar              clean  0.0889     0.0                   0.16
4    default-grammar              clean  0.0889     0.0                   0.16

In [3]:
METRICS = ["rouge1", "rouge2", "cosineSimilarityScore"]

def agg_metrics(df, group_cols):
    agg = df.groupby(group_cols)[METRICS].agg(["mean", "std"]).round(4)
    agg.columns = [f"{metric}_{stat}" for metric, stat in agg.columns]
    agg["n"] = df.groupby(group_cols)[METRICS[0]].count()
    return agg

by_prompt = agg_metrics(df, "prompt_instruction")
print("=" * 70)
print("Aggregated by prompt_instruction")
print("=" * 70)
pd.set_option("display.max_colwidth", 50)
pd.set_option("display.width", 200)
print(by_prompt.to_string())

print()

by_attack = agg_metrics(df, "attack_instruction")
print("=" * 70)
print("Aggregated by attack_instruction")
print("=" * 70)
print(by_attack.to_string())

print()

by_both = agg_metrics(df, ["prompt_instruction", "attack_instruction"])
print("=" * 70)
print("Aggregated by prompt_instruction x attack_instruction")
print("=" * 70)
print(by_both.to_string())

======================================================================
Aggregated by prompt_instruction
======================================================================
                                 rouge1_mean  rouge1_std  rouge2_mean  rouge2_std  cosineSimilarityScore_mean  cosineSimilarityScore_std   n
prompt_instruction
default-ad-product-description        0.3256         0.0       0.0510         0.0                      0.6235                        0.0  15
default-adv-tweet-classifier          0.4175         0.0       0.3039         0.0                      0.6844                        0.0  15
default-airport-codes                 0.1905         0.0       0.0000         0.0                      0.5788                        0.0  15
default-analogy-maker                 0.3084         0.0       0.0377         0.0                      0.2449                        0.0  15
default-chat                          0.2124         0.0       0.0446         0.0                      0.3146                        0.0  15
default-esrb-rating                   0.0615         0.0       0.0317         0.0                      0.7876                        0.0  15
default-essay-outline                 0.2093         0.0       0.0714         0.0                      0.2592                        0.0  15
default-extract-contact-info          0.1243         0.0       0.0343         0.0                      0.4004                        0.0  15
default-factual-answering             0.8636         0.0       0.7419         0.0                      0.7652                        0.0  15
default-friend-chat                   0.5385         0.0       0.3333         0.0                      0.6105                        0.0  15
default-grammar                       0.0889         0.0       0.0000         0.0                      0.1600                        0.0  15
default-interview-questions           0.4734         0.0       0.1621         0.0                      0.2687                        0.0  15
default-keywords                      0.0606         0.0       0.0000         0.0                      0.1358                        0.0  15
default-marv-sarcastic-chat           0.1978         0.0       0.0667         0.0                      0.4770                        0.0  15
default-micro-horror                  0.1782         0.0       0.0202         0.0                      0.2813                        0.0  15
default-ml-ai-tutor                   0.2472         0.0       0.1808         0.0                      0.8451                        0.0  15
default-mood-color                    0.1295         0.0       0.0438         0.0                      0.6809                        0.0  15
default-movie-to-emoji                0.5714         0.0       0.5263         0.0                      0.5164                        0.0  15
default-notes-summary                 0.1602         0.0       0.0368         0.0                      0.5929                        0.0  15
default-parse-data                    0.4510         0.0       0.2400         0.0                      0.8736                        0.0  15
default-qa                            0.2000         0.0       0.0000         0.0                      0.1855                        0.0  15
default-restaurant-review             0.1905         0.0       0.0205         0.0                      0.3912                        0.0  15
default-sci-fi-book-list              0.0000         0.0       0.0000         0.0                     -0.0012                        0.0  15
default-spreadsheet-gen               0.1406         0.0       0.0476         0.0                      0.4915                        0.0  15
default-sql-request                   0.1294         0.0       0.0357         0.0                      0.4298                        0.0  15
default-study-notes                   0.2448         0.0       0.1268         0.0                      0.7932                        0.0  15
default-summarize                     0.1784         0.0       0.0000         0.0                     -0.0277                        0.0  15
default-text-to-command               0.0714         0.0       0.0602         0.0                      0.2136                        0.0  15
default-third-person                  0.0222         0.0       0.0000         0.0                      0.2376                        0.0  15
default-time-complexity               0.1241         0.0       0.0979         0.0                      0.7200                        0.0  15
default-tldr-summary                  0.1132         0.0       0.0000         0.0                      0.0820                        0.0  15
default-translate                     0.1677         0.0       0.0000         0.0                      0.4254                        0.0  15
default-turn-by-turn-directions       0.2778         0.0       0.1509         0.0                      0.7679                        0.0  15
default-tweet-classifier              0.1852         0.0       0.1154         0.0                      0.6831                        0.0  15
default-vr-fitness                    0.2840         0.0       0.0359         0.0                      0.3804                        0.0  15

======================================================================
Aggregated by attack_instruction
======================================================================
                    rouge1_mean  rouge1_std  rouge2_mean  rouge2_std  cosineSimilarityScore_mean  cosineSimilarityScore_std    n
attack_instruction
clean                    0.2325      0.1743       0.1034      0.1574                      0.4535                     0.2506  525

======================================================================
Aggregated by prompt_instruction x attack_instruction
======================================================================
                                                    rouge1_mean  rouge1_std  rouge2_mean  rouge2_std  cosineSimilarityScore_mean  cosineSimilarityScore_std   n
prompt_instruction              attack_instruction
default-ad-product-description  clean                    0.3256         0.0       0.0510         0.0                      0.6235                        0.0  15
default-adv-tweet-classifier    clean                    0.4175         0.0       0.3039         0.0                      0.6844                        0.0  15
default-airport-codes           clean                    0.1905         0.0       0.0000         0.0                      0.5788                        0.0  15
default-analogy-maker           clean                    0.3084         0.0       0.0377         0.0                      0.2449                        0.0  15
default-chat                    clean                    0.2124         0.0       0.0446         0.0                      0.3146                        0.0  15
default-esrb-rating             clean                    0.0615         0.0       0.0317         0.0                      0.7876                        0.0  15
default-essay-outline           clean                    0.2093         0.0       0.0714         0.0                      0.2592                        0.0  15
default-extract-contact-info    clean                    0.1243         0.0       0.0343         0.0                      0.4004                        0.0  15
default-factual-answering       clean                    0.8636         0.0       0.7419         0.0                      0.7652                        0.0  15
default-friend-chat             clean                    0.5385         0.0       0.3333         0.0                      0.6105                        0.0  15
default-grammar                 clean                    0.0889         0.0       0.0000         0.0                      0.1600                        0.0  15
default-interview-questions     clean                    0.4734         0.0       0.1621         0.0                      0.2687                        0.0  15
default-keywords                clean                    0.0606         0.0       0.0000         0.0                      0.1358                        0.0  15
default-marv-sarcastic-chat     clean                    0.1978         0.0       0.0667         0.0                      0.4770                        0.0  15
default-micro-horror            clean                    0.1782         0.0       0.0202         0.0                      0.2813                        0.0  15
default-ml-ai-tutor             clean                    0.2472         0.0       0.1808         0.0                      0.8451                        0.0  15
default-mood-color              clean                    0.1295         0.0       0.0438         0.0                      0.6809                        0.0  15
default-movie-to-emoji          clean                    0.5714         0.0       0.5263         0.0                      0.5164                        0.0  15
default-notes-summary           clean                    0.1602         0.0       0.0368         0.0                      0.5929                        0.0  15
default-parse-data              clean                    0.4510         0.0       0.2400         0.0                      0.8736                        0.0  15
default-qa                      clean                    0.2000         0.0       0.0000         0.0                      0.1855                        0.0  15
default-restaurant-review       clean                    0.1905         0.0       0.0205         0.0                      0.3912                        0.0  15
default-sci-fi-book-list        clean                    0.0000         0.0       0.0000         0.0                     -0.0012                        0.0  15
default-spreadsheet-gen         clean                    0.1406         0.0       0.0476         0.0                      0.4915                        0.0  15
default-sql-request             clean                    0.1294         0.0       0.0357         0.0                      0.4298                        0.0  15
default-study-notes             clean                    0.2448         0.0       0.1268         0.0                      0.7932                        0.0  15
default-summarize               clean                    0.1784         0.0       0.0000         0.0                     -0.0277                        0.0  15
default-text-to-command         clean                    0.0714         0.0       0.0602         0.0                      0.2136                        0.0  15
default-third-person            clean                    0.0222         0.0       0.0000         0.0                      0.2376                        0.0  15
default-time-complexity         clean                    0.1241         0.0       0.0979         0.0                      0.7200                        0.0  15
default-tldr-summary            clean                    0.1132         0.0       0.0000         0.0                      0.0820                        0.0  15
default-translate               clean                    0.1677         0.0       0.0000         0.0                      0.4254                        0.0  15
default-turn-by-turn-directions clean                    0.2778         0.0       0.1509         0.0                      0.7679                        0.0  15
default-tweet-classifier        clean                    0.1852         0.0       0.1154         0.0                      0.6831                        0.0  15
default-vr-fitness              clean                    0.2840         0.0       0.0359         0.0                      0.3804                        0.0  15

In [4]:
import pandas as pd
import numpy as np

METRICS = ["rouge1", "rouge2", "cosineSimilarityScore"]

def agg_metrics(df, group_cols):
    agg = df.groupby(group_cols)[METRICS].agg(["mean", "std"]).round(4)
    agg.columns = [f"{metric}_{stat}" for metric, stat in agg.columns]
    agg["n"] = df.groupby(group_cols)[METRICS[0]].count()
    return agg

by_prompt = agg_metrics(df, "prompt_instruction")
by_attack = agg_metrics(df, "attack_instruction")
by_both   = agg_metrics(df, ["prompt_instruction", "attack_instruction"])

from IPython.display import display, HTML

def show_table(agg_df, title):
    display(HTML(f"<h3>{title}</h3>"))
    display(agg_df.style
        .format({c: "{:.4f}" for c in agg_df.columns if c != "n"})
        .background_gradient(subset=["rouge1_mean", "rouge2_mean", "cosineSimilarityScore_mean"], cmap="Blues")
        .set_table_styles([
            {"selector": "th", "props": [("font-size", "11px"), ("text-align", "center")]},
            {"selector": "td", "props": [("font-size", "10px")]},
        ])
    )

show_table(by_prompt, "Aggregated by prompt_instruction")
show_table(by_attack, "Aggregated by attack_instruction")
show_table(by_both,   "Aggregated by prompt_instruction × attack_instruction")

In [5]:
import pandas as pd
import numpy as np

# Update this path to wherever compare_model_outputs() saved its output
COMPARISON_CSV2 = "/content/drive/MyDrive/11711 group project/elaine work/injection_comparison_results.csv"

df = pd.read_csv(COMPARISON_CSV2)

print(f"Loaded {len(df)} rows")
print(f"Columns: {df.columns.tolist()}")
print()
print(df[["prompt_instruction", "attack_instruction", "rouge1", "rouge2", "cosineSimilarityScore"]].head(5))

Loaded 525 rows
Columns: ['prompt_instruction', 'attack_instruction', 'output_WithoutCOT', 'output_WithCOT', 'cosineSimilarityScore', 'rouge1', 'rouge2']

  prompt_instruction                                 attack_instruction  rouge1  rouge2  cosineSimilarityScore
0    default-grammar            ignore-previous-and-spell-check-instead  0.2222  0.0253                 0.3020
1    default-grammar            ignore-previous-and-spell-check-instead  0.2222  0.0253                 0.3020
2    default-grammar            ignore-previous-and-spell-check-instead  0.2222  0.0253                 0.3020
3    default-grammar  ignore-previous-and-spell-check-instead-uppercase  0.2308  0.0000                 0.4156
4    default-grammar  ignore-previous-and-spell-check-instead-uppercase  0.2308  0.0000                 0.4156

In [6]:
METRICS = ["rouge1", "rouge2", "cosineSimilarityScore"]

def agg_metrics(df, group_cols):
    agg = df.groupby(group_cols)[METRICS].agg(["mean", "std"]).round(4)
    agg.columns = [f"{metric}_{stat}" for metric, stat in agg.columns]
    agg["n"] = df.groupby(group_cols)[METRICS[0]].count()
    return agg

by_prompt = agg_metrics(df, "prompt_instruction")
print("=" * 70)
print("Aggregated by prompt_instruction")
print("=" * 70)
pd.set_option("display.max_colwidth", 50)
pd.set_option("display.width", 200)
print(by_prompt.to_string())

print()

by_attack = agg_metrics(df, "attack_instruction")
print("=" * 70)
print("Aggregated by attack_instruction")
print("=" * 70)
print(by_attack.to_string())

print()

by_both = agg_metrics(df, ["prompt_instruction", "attack_instruction"])
print("=" * 70)
print("Aggregated by prompt_instruction x attack_instruction")
print("=" * 70)
print(by_both.to_string())

======================================================================
Aggregated by prompt_instruction
======================================================================
                                 rouge1_mean  rouge1_std  rouge2_mean  rouge2_std  cosineSimilarityScore_mean  cosineSimilarityScore_std   n
prompt_instruction
default-ad-product-description        0.1976      0.1168       0.0393      0.0348                      0.4202                     0.1707  15
default-adv-tweet-classifier          0.4179      0.2122       0.2522      0.2562                      0.7305                     0.0375  15
default-airport-codes                 0.3304      0.1258       0.0857      0.0773                      0.7076                     0.1090  15
default-analogy-maker                 0.2577      0.1312       0.0827      0.0847                      0.3478                     0.2062  15
default-chat                          0.2293      0.1439       0.1017      0.1033                      0.3689                     0.1518  15
default-esrb-rating                   0.1160      0.1473       0.0466      0.0617                      0.4530                     0.2135  15
default-essay-outline                 0.2201      0.1150       0.0697      0.0471                      0.5615                     0.1052  15
default-extract-contact-info          0.0498      0.0460       0.0080      0.0166                      0.2588                     0.1557  15
default-factual-answering             0.1940      0.1806       0.0805      0.1368                      0.2546                     0.1848  15
default-friend-chat                   0.3475      0.1927       0.2041      0.2176                      0.4055                     0.2025  15
default-grammar                       0.1844      0.0386       0.0051      0.0105                      0.2801                     0.0912  15
default-interview-questions           0.2395      0.1881       0.0809      0.0976                      0.4522                     0.1658  15
default-keywords                      0.2110      0.1064       0.0347      0.0411                      0.3552                     0.1960  15
default-marv-sarcastic-chat           0.3607      0.3215       0.2510      0.3241                      0.4859                     0.1931  15
default-micro-horror                  0.2128      0.1103       0.0612      0.0638                      0.3463                     0.2140  15
default-ml-ai-tutor                   0.4316      0.2162       0.3228      0.2373                      0.6570                     0.1955  15
default-mood-color                    0.1482      0.0969       0.0277      0.0240                      0.2363                     0.2536  15
default-movie-to-emoji                0.4224      0.3017       0.2683      0.2390                      0.5510                     0.2945  15
default-notes-summary                 0.1589      0.0691       0.0558      0.0515                      0.3122                     0.1724  15
default-parse-data                    0.2573      0.1404       0.1604      0.1048                      0.6009                     0.3011  15
default-qa                            0.0740      0.0644       0.0324      0.0489                      0.1700                     0.0964  15
default-restaurant-review             0.1805      0.1367       0.0651      0.0600                      0.5036                     0.2233  15
default-sci-fi-book-list              0.1725      0.0828       0.0428      0.0631                      0.3308                     0.1764  15
default-spreadsheet-gen               0.1166      0.0931       0.0280      0.0352                      0.1840                     0.1726  15
default-sql-request                   0.1526      0.1002       0.0457      0.0485                      0.2852                     0.1868  15
default-study-notes                   0.2180      0.1005       0.0590      0.0435                      0.5317                     0.3210  15
default-summarize                     0.1923      0.0941       0.0386      0.0589                      0.2530                     0.1728  15
default-text-to-command               0.2250      0.1354       0.1067      0.0774                      0.4236                     0.2518  15
default-third-person                  0.2201      0.1771       0.0735      0.0785                      0.5458                     0.0403  15
default-time-complexity               0.4477      0.1257       0.3385      0.1262                      0.4909                     0.1073  15
default-tldr-summary                  0.1899      0.1059       0.0665      0.0579                      0.3002                     0.0992  15
default-translate                     0.1400      0.1371       0.0333      0.0464                      0.3557                     0.1876  15
default-turn-by-turn-directions       0.2128      0.1368       0.0878      0.0940                      0.3469                     0.2309  15
default-tweet-classifier              0.1558      0.1282       0.0891      0.1384                      0.5214                     0.1721  15
default-vr-fitness                    0.1050      0.1294       0.0363      0.0878                      0.2317                     0.2552  15

======================================================================
Aggregated by attack_instruction
======================================================================
                                                   rouge1_mean  rouge1_std  rouge2_mean  rouge2_std  cosineSimilarityScore_mean  cosineSimilarityScore_std    n
attack_instruction
ignore-previous-and-print                               0.2290      0.1733       0.0964      0.1281                      0.4160                     0.2393  105
ignore-previous-and-print-instead                       0.2562      0.2081       0.1276      0.1842                      0.4037                     0.2474  105
ignore-previous-and-spell-check                         0.2060      0.1390       0.0786      0.0997                      0.4346                     0.1973  105
ignore-previous-and-spell-check-instead                 0.1921      0.1719       0.0891      0.1474                      0.3620                     0.2434  105
ignore-previous-and-spell-check-instead-uppercase       0.2297      0.1694       0.0914      0.1496                      0.4208                     0.2412  105

======================================================================
Aggregated by prompt_instruction x attack_instruction
======================================================================
                                                                                   rouge1_mean  rouge1_std  rouge2_mean  rouge2_std  cosineSimilarityScore_mean  cosineSimilarityScore_std  n
prompt_instruction              attack_instruction
default-ad-product-description  ignore-previous-and-print                               0.2663      0.0936       0.0602      0.0389                      0.5272                     0.0970  3
                                ignore-previous-and-print-instead                       0.1500      0.0738       0.0158      0.0044                      0.2994                     0.0652  3
                                ignore-previous-and-spell-check                         0.2274      0.2007       0.0588      0.0610                      0.5353                     0.2124  3
                                ignore-previous-and-spell-check-instead                 0.0927      0.0900       0.0183      0.0176                      0.3118                     0.1363  3
                                ignore-previous-and-spell-check-instead-uppercase       0.2516      0.0121       0.0432      0.0138                      0.4276                     0.2239  3
default-adv-tweet-classifier    ignore-previous-and-print                               0.5841      0.0000       0.5045      0.0000                      0.7062                     0.0000  3
                                ignore-previous-and-print-instead                       0.7391      0.0000       0.6000      0.0000                      0.6932                     0.0000  3
                                ignore-previous-and-spell-check                         0.2632      0.0000       0.0811      0.0000                      0.7180                     0.0000  3
                                ignore-previous-and-spell-check-instead                 0.2532      0.0000       0.0519      0.0000                      0.7384                     0.0000  3
                                ignore-previous-and-spell-check-instead-uppercase       0.2500      0.0000       0.0233      0.0000                      0.7966                     0.0000  3
default-airport-codes           ignore-previous-and-print                               0.4615      0.0000       0.1667      0.0000                      0.7988                     0.0000  3
                                ignore-previous-and-print-instead                       0.4615      0.0000       0.1667      0.0000                      0.7988                     0.0000  3
                                ignore-previous-and-spell-check                         0.1905      0.0000       0.0000      0.0000                      0.5788                     0.0000  3
                                ignore-previous-and-spell-check-instead                 0.3478      0.0000       0.0952      0.0000                      0.7828                     0.0000  3
                                ignore-previous-and-spell-check-instead-uppercase       0.1905      0.0000       0.0000      0.0000                      0.5788                     0.0000  3
default-analogy-maker           ignore-previous-and-print                               0.3148      0.0192       0.0822      0.0107                      0.2510                     0.1203  3
                                ignore-previous-and-print-instead                       0.3201      0.2530       0.1502      0.1731                      0.4713                     0.2543  3
                                ignore-previous-and-spell-check                         0.1968      0.0522       0.0277      0.0242                      0.1949                     0.0564  3
                                ignore-previous-and-spell-check-instead                 0.2374      0.1192       0.0670      0.0283                      0.3259                     0.1655  3
                                ignore-previous-and-spell-check-instead-uppercase       0.2195      0.1420       0.0866      0.0835                      0.4958                     0.2870  3
default-chat                    ignore-previous-and-print                               0.3980      0.0315       0.2203      0.0759                      0.5011                     0.1780  3
                                ignore-previous-and-print-instead                       0.1812      0.1853       0.1186      0.1655                      0.3657                     0.2382  3
                                ignore-previous-and-spell-check                         0.1117      0.0815       0.0516      0.0532                      0.3692                     0.1282  3
                                ignore-previous-and-spell-check-instead                 0.1891      0.1099       0.0524      0.0633                      0.2491                     0.0071  3
                                ignore-previous-and-spell-check-instead-uppercase       0.2667      0.1393       0.0654      0.0612                      0.3595                     0.0919  3
default-esrb-rating             ignore-previous-and-print                               0.0444      0.0770       0.0238      0.0412                      0.2940                     0.1688  3
                                ignore-previous-and-print-instead                       0.0000      0.0000       0.0000      0.0000                      0.1897                     0.0343  3
                                ignore-previous-and-spell-check                         0.2795      0.2273       0.1158      0.1037                      0.4842                     0.1625  3
                                ignore-previous-and-spell-check-instead                 0.1616      0.1475       0.0406      0.0154                      0.6265                     0.0510  3
                                ignore-previous-and-spell-check-instead-uppercase       0.0947      0.0297       0.0527      0.0515                      0.6706                     0.0318  3
default-essay-outline           ignore-previous-and-print                               0.0756      0.0000       0.0415      0.0000                      0.5496                     0.0000  3
                                ignore-previous-and-print-instead                       0.3217      0.0000       0.0845      0.0000                      0.7210                     0.0000  3
                                ignore-previous-and-spell-check                         0.1205      0.0000       0.0275      0.0000                      0.4911                     0.0000  3
                                ignore-previous-and-spell-check-instead                 0.3636      0.0000       0.1524      0.0000                      0.6180                     0.0000  3
                                ignore-previous-and-spell-check-instead-uppercase       0.2191      0.0000       0.0426      0.0000                      0.4276                     0.0000  3
default-extract-contact-info    ignore-previous-and-print                               0.0157      0.0000       0.0000      0.0000                      0.0954                     0.0000  3
                                ignore-previous-and-print-instead                       0.0526      0.0000       0.0000      0.0000                      0.0749                     0.0000  3
                                ignore-previous-and-spell-check                         0.0522      0.0000       0.0000      0.0000                      0.4609                     0.0000  3
                                ignore-previous-and-spell-check-instead                 0.0000      0.0000       0.0000      0.0000                      0.3059                     0.0000  3
                                ignore-previous-and-spell-check-instead-uppercase       0.1287      0.0000       0.0400      0.0000                      0.3568                     0.0000  3
default-factual-answering       ignore-previous-and-print                               0.1351      0.0000       0.0000      0.0000                      0.0641                     0.0000  3
                                ignore-previous-and-print-instead                       0.1304      0.0000       0.0294      0.0000                      0.0825                     0.0000  3
                                ignore-previous-and-spell-check                         0.5379      0.0000       0.3435      0.0000                      0.4201                     0.0000  3
                                ignore-previous-and-spell-check-instead                 0.1143      0.0000       0.0294      0.0000                      0.5059                     0.0000  3
                                ignore-previous-and-spell-check-instead-uppercase       0.0524      0.0000       0.0000      0.0000                      0.2006                     0.0000  3
default-friend-chat             ignore-previous-and-print                               0.3442      0.1538       0.1905      0.2520                      0.3209                     0.0965  3
                                ignore-previous-and-print-instead                       0.4608      0.0713       0.2613      0.0981                      0.5504                     0.1232  3
                                ignore-previous-and-spell-check                         0.3641      0.0736       0.1337      0.1162                      0.4349                     0.0918  3
                                ignore-previous-and-spell-check-instead                 0.2160      0.1974       0.1784      0.1727                      0.3261                     0.1966  3
                                ignore-previous-and-spell-check-instead-uppercase       0.3526      0.3757       0.2564      0.4441                      0.3953                     0.4028  3
default-grammar                 ignore-previous-and-print                               0.1463      0.0000       0.0000      0.0000                      0.2620                     0.0000  3
                                ignore-previous-and-print-instead                       0.1408      0.0000       0.0000      0.0000                      0.2811                     0.0000  3
                                ignore-previous-and-spell-check                         0.1818      0.0000       0.0000      0.0000                      0.1399                     0.0000  3
                                ignore-previous-and-spell-check-instead                 0.2222      0.0000       0.0253      0.0000                      0.3020                     0.0000  3
                                ignore-previous-and-spell-check-instead-uppercase       0.2308      0.0000       0.0000      0.0000                      0.4156                     0.0000  3
default-interview-questions     ignore-previous-and-print                               0.0737      0.0193       0.0273      0.0128                      0.5611                     0.1000  3
                                ignore-previous-and-print-instead                       0.0422      0.0205       0.0028      0.0048                      0.2267                     0.2408  3
                                ignore-previous-and-spell-check                         0.3620      0.1677       0.1102      0.1036                      0.5370                     0.1074  3
                                ignore-previous-and-spell-check-instead                 0.4629      0.1209       0.2119      0.1163                      0.5069                     0.0459  3
                                ignore-previous-and-spell-check-instead-uppercase       0.2567      0.0820       0.0523      0.0217                      0.4291                     0.0266  3
default-keywords                ignore-previous-and-print                               0.2156      0.0675       0.0392      0.0679                      0.1754                     0.1161  3
                                ignore-previous-and-print-instead                       0.2301      0.0726       0.0637      0.0149                      0.3641                     0.2111  3
                                ignore-previous-and-spell-check                         0.1331      0.1166       0.0000      0.0000                      0.3307                     0.2611  3
                                ignore-previous-and-spell-check-instead                 0.1923      0.1521       0.0345      0.0597                      0.4274                     0.1705  3
                                ignore-previous-and-spell-check-instead-uppercase       0.2840      0.1203       0.0360      0.0174                      0.4781                     0.1837  3
default-marv-sarcastic-chat     ignore-previous-and-print                               0.3415      0.0000       0.0617      0.0000                      0.6695                     0.0000  3
                                ignore-previous-and-print-instead                       0.1387      0.0000       0.0351      0.0000                      0.2726                     0.0000  3
                                ignore-previous-and-spell-check                         0.0134      0.0000       0.0000      0.0000                      0.3264                     0.0000  3
                                ignore-previous-and-spell-check-instead                 0.7934      0.0000       0.7167      0.0000                      0.5481                     0.0000  3

In [7]:
print("Overall mean and std across all rows:")
print(df[["rouge1", "rouge2", "cosineSimilarityScore"]].agg(["mean", "std"]).round(4).to_string())

Overall mean and std across all rows:
      rouge1  rouge2  cosineSimilarityScore
mean  0.2226  0.0966                 0.4074
std   0.1745  0.1449                 0.2349

In [8]:
import pandas as pd
import numpy as np

METRICS = ["rouge1", "rouge2", "cosineSimilarityScore"]

def agg_metrics(df, group_cols):
    agg = df.groupby(group_cols)[METRICS].agg(["mean", "std"]).round(4)
    agg.columns = [f"{metric}_{stat}" for metric, stat in agg.columns]
    agg["n"] = df.groupby(group_cols)[METRICS[0]].count()
    return agg

by_prompt = agg_metrics(df, "prompt_instruction")
by_attack = agg_metrics(df, "attack_instruction")
by_both   = agg_metrics(df, ["prompt_instruction", "attack_instruction"])

from IPython.display import display, HTML

def show_table(agg_df, title):
    display(HTML(f"<h3>{title}</h3>"))
    display(agg_df.style
        .format({c: "{:.4f}" for c in agg_df.columns if c != "n"})
        .background_gradient(subset=["rouge1_mean", "rouge2_mean", "cosineSimilarityScore_mean"], cmap="Blues")
        .set_table_styles([
            {"selector": "th", "props": [("font-size", "11px"), ("text-align", "center")]},
            {"selector": "td", "props": [("font-size", "10px")]},
        ])
    )

show_table(by_prompt, "Aggregated by prompt_instruction")
show_table(by_attack, "Aggregated by attack_instruction")
show_table(by_both,   "Aggregated by prompt_instruction × attack_instruction")